<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>

<channel>
	<title>ScruplesDecor &#187; Productos</title>
	<atom:link href="http://www.scruplesdecor.com/shop/feed/?product_cat=ben-holly" rel="self" type="application/rss+xml" />
	<link>http://www.scruplesdecor.com</link>
	<description>Algodon Egipico, Fundas Nordicas, Cortinas</description>
	<lastBuildDate>Wed, 23 Sep 2015 20:12:28 +0000</lastBuildDate>
	<language>es-ES</language>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>http://wordpress.org/?v=4.3</generator>
	<item>
		<title>Funda nordica Ben &#038; Holly Los Elfos Cama 90</title>
		<link>http://www.scruplesdecor.com/product/funda-nordica-ben-holly-los-elfos-cama-90/</link>
		<comments>http://www.scruplesdecor.com/product/funda-nordica-ben-holly-los-elfos-cama-90/#comments</comments>
		<pubDate>Tue, 24 May 2011 16:26:39 +0000</pubDate>
		<dc:creator><![CDATA[]]></dc:creator>
		
		<guid isPermaLink="false">https://www.scruplesdecor.com/build/?post_type=product&#038;p=21505</guid>
		<description><![CDATA[ -  50% algodon, 50% poliéster
 -   Funda 137 x 200cms, funda almohada 46 x  
     75cms
 -   Multi
 -   Lavar a maquina
]]></description>
				<content:encoded><![CDATA[<p>..</p>
]]></content:encoded>
			<wfw:commentRss>http://www.scruplesdecor.com/product/funda-nordica-ben-holly-los-elfos-cama-90/feed/</wfw:commentRss>
		<slash:comments>0</slash:comments>
		</item>
		<item>
		<title>Funda nordica Ben &#038; Holly Los Elfos Cama 90cms</title>
		<link>http://www.scruplesdecor.com/product/funda-nordica-ben-holly-los-elfos-cama-90cms/</link>
		<comments>http://www.scruplesdecor.com/product/funda-nordica-ben-holly-los-elfos-cama-90cms/#comments</comments>
		<pubDate>Thu, 02 Jun 2011 17:54:14 +0000</pubDate>
		<dc:creator><![CDATA[]]></dc:creator>
		
		<guid isPermaLink="false">https://www.scruplesdecor.com/build/?post_type=product&#038;p=21633</guid>
		<description><![CDATA[ -   50% algodon, 50% poliéster
 -   Funda 137 x 200cms, funda de   
     almohada 50 x 75cms approx
 -   Multi
 -   Lavar a maquina



]]></description>
				<content:encoded><![CDATA[<p>.</p>
]]></content:encoded>
			<wfw:commentRss>http://www.scruplesdecor.com/product/funda-nordica-ben-holly-los-elfos-cama-90cms/feed/</wfw:commentRss>
		<slash:comments>0</slash:comments>
		</item>
	</channel>
</rss>

<!-- Dynamic page generated in 0.654 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2015-09-28 09:27:41 -->
