<?php
namespace Aelia\WC;
if(!defined('ABSPATH')) exit; // Exit if accessed directly

/**
 * Class to represent Admin messages generated by the plugin.
 *
 * @since 1.6.1.150728
 */
class Admin_Message extends Message {
	// @var string The ID of the sender who created the message.
	public $sender_id;

	/**
	 * Class constructor.
	 *
	 * @param string sender_id The ID of the sender. Used to distinguish messages
	 * with the same code.
	 * @param int level The message level.
	 * @param string message The message.
	 * @param string code The message code.
	 * @param bool dismissable Indicates if the message can be dismissed.
	 */
	public function __construct($sender_id, $level, $message, $code = '', $dismissable = false) {
		parent::__construct($level, $message, $code, $dismissable);
		$this->sender_id = $sender_id;
	}
}
